FROM ubuntu:22.04

LABEL Author="shoaib"

RUN apt update
RUN apt install openjdk-11-jre-headless -y
RUN apt install tar -y
RUN apt install unzip -y
RUN apt install wget -y
RUN wget https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.99/bin/apache-tomcat-8.5.99.tar.gz

RUN tar -xzvf apache-tomcat-8.5.99.tar.gz
WORKDIR apache-tomcat-8.5.99

ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/mysql-connector.jar lib/mysql-connector.jar
COPY context.xml conf/context.xml
COPY student.war webapps/student.war

EXPOSE 8080

CMD ["bin/catalina.sh", "run"]
